server:
  port: 8989
spring:
  datasource:
#    url: jdbc:mysql://43.142.16.126:3306/blog?characterEncoding=utf-8&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: '020628'
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
#    host: 127.0.0.1
#    host: 43.142.16.126
    host: 192.168.109.128
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
oss:
  accessKey: vZYB_T4HzvvmSXu1xDVwiJA8hEJrYD53CMgN-IiI
  secretKey: VrbDH-MvhNCi-uXFVoGjLzvZXdDr3C2EwvSuky6m
  bucket: xin-blog